version: '3.9'
services:
  jenkins:
    restart: on-failure:10
    image: jenkins/jenkins:latest
    container_name: my-jenkins
    ports:
      - 8099:8080
    volumes:
      - ~/apps/jenkins:/var/jenkins_home