spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password: user
  h2:
    console:
      enabled:
        true
      path:
        /h2

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher